name: Box CI

on:
  [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
#      - name: Copy config
#        run: cp resources/application.template.conf resources/application.conf
#      - name: Run tests
#        env:
#          TEST_DB_URL: ${{ secrets.TEST_DB_URL }}
#          TEST_DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
#          DB_URL: ${{ secrets.TEST_DB_URL }}
#          DB_SCHEMA: 'public'
#          DB_USER: 'postgres'
#          DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
#          BOX_DB_URL: ${{ secrets.TEST_DB_URL }}
#          BOX_DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
#          BOX_DB_SCHEMA: 'box'
#          BOX_DB_USER: 'postgres'
#        run: sbt server/test