name: Box CI

on:
  [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest
    env:
      # define Java options for both official sbt and sbt-extras
      JAVA_OPTS: -Xms4G -Xmx4G -Xss10M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8 -XX:+CMSClassUnloadingEnabled
      JVM_OPTS: -Xms4G -Xmx4G -Xss10M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8 -XX:+CMSClassUnloadingEnabled
      NODE_OPTIONS: --max-old-space-size=2048

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.8"
      - name: Node 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.19.0
      - name: Setup client test env
        run: npm install
      - name: Run tests server
        run: |
          sbt codegen/clean
          sbt server/clean
          sbt client/clean
          sbt server/test
      - name: Run tests client
        run: sbt client/test