name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  push:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get Previous tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@master"
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish to bintray
        #run: sbt -J-Xmx4G -J-XX:MaxMetaspaceSize=1G -J-XX:MaxPermSize=1G -J-XX:+CMSClassUnloadingEnabled -J-Xss10m  -Dbintray.user=minettiandrea -Dbintray.pass=${{ secrets.BINTRAY_PASSWORD  }} publishAll
        # I need to start sbt Using java or I get an error of webpack
        run: java -Xms2G -Xmx4G -Xss10M -XX:+CMSClassUnloadingEnabled -Dbintray.user=minettiandrea -Dbintray.pass=${{ secrets.BINTRAY_PASSWORD  }} -classpath /usr/share/sbt/bin/sbt-launch.jar xsbt.boot.Boot publishAll
