name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  push:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get Previous tag
          id: previoustag
          uses: "WyriHaximus/github-action-get-previous-tag@master"
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build image
          run: sbt box

      - uses: ncipollo/release-action@v1
          with:
            artifacts: "server/target/universal/server-${{ steps.previoustag.outputs.tag }}.zip,server/target/scala-2.12/server_2.12-${{ steps.previoustag.outputs.tag }}.war"
            token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build docker image
        run: sbt boxDocker

      - uses: azure/docker-login@v1
        with:
          username: 'minettiandrea'
          password: ${{ secrets.DOCKERHUB_PASSWORD  }}

      - name: Push docker image
        run:
          docker push boxframework/box-framework:${{ steps.previoustag.outputs.tag }}

