name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  push:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get Previous tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@master"
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish to bintray
        run: sbt -Xms2048M -Xmx4024M -Xss10M -XX:+CMSClassUnloadingEnabled  -Dbintray.user=minettiandrea -Dbintray.pass=${{ secrets.BINTRAY_PASSWORD  }} publishAll
