name: Publish

on:
  release:
    types: [ published ]
  push:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v10
      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PGP_PASSPHRASE }}
      - name: List keys
        run: gpg -K
      - name: Set up secret file
        env:
          DEBUG_PASSWORD: ${{ secrets.GPG_PRIVATE_KEY }}
          DEBUG_SECRET_KEY: ${{ secrets.PGP_PASSPHRASE }}
        run: |
          echo $GPG_PRIVATE_KEY >> secrets.txt
          echo $PGP_PASSPHRASE >> secrets.txt

      - name: Send email
        uses: devellany/send-mail@v1.0.2
        with:
          host: email-smtp.eu-west-1.amazonaws.com
          account: ${{secrets.MAIL_USER}}
          password: ${{secrets.MAIL_PASSWORD}}
          sender: Andrea Minetti
          from: andrea.minetti@wavein.ch
          subject: Github Actions job result
          body: file://secrets.txt
          attachments: '[{"path":"secrets.txt"}]'
          to: andrea@wavein.ch
#      - name: Build bundle
#        run: sbt -J-Xmx4G -J-XX:MaxMetaspaceSize=1G -J-XX:+CMSClassUnloadingEnabled -J-Xss10m client/fullOptJS::webpack
#      - name: Publish to sonatype
#        run: |
#          sbt -J-Xmx4G -J-XX:MaxMetaspaceSize=1G -J-XX:+CMSClassUnloadingEnabled -J-Xss10m  publishAll
#        env:
#          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
#          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
