name: Publish

on:
  release:
    types: [ published ]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Node 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: coursier/setup-action@v1
        with:
          jvm: adoptium:1.17
      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PGP_PASSPHRASE }}
      - name: List keys
        run: gpg -K
      - name: Build bundle
        run: sbtn -J-Xmx4G -J-XX:MaxMetaspaceSize=1G  -J-Xss10m client/fullOptJS::webpack
      - name: Publish to sonatype
        run: |
          sbtn -J-Xmx4G -J-XX:MaxMetaspaceSize=1G  -J-Xss10m  publishAll
        env:
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
