name: Release

on:
  push:
    branches: [master]
    tags: ["*"]
  release:
    types: [ published ]

jobs:
  push:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
          with:
            fetch-depth: 0
      - uses: olafurpg/setup-scala@v10
      - uses: olafurpg/setup-gpg@v3
      - name: Build bundle
        run: sbt -J-Xmx4G -J-XX:MaxMetaspaceSize=1G -J-XX:+CMSClassUnloadingEnabled -J-Xss10m client/fullOptJS::webpack
      - name: Publish to sonatype
        run: |
          sbt -J-Xmx4G -J-XX:MaxMetaspaceSize=1G -J-XX:+CMSClassUnloadingEnabled -J-Xss10m  ci-release
        env:
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_HOST: s01.oss.sonatype.org
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
